### ISSUE TITLE
Failed to parse JSON response错误

### ISSUE THREAD

**Issue by celing76** [kekxv/AiReviewPR#5]
你好，我重新试了一下，在工作流里面 code review这个地方运行过程中，模型服务正常运行，查看ollama的日志也能看到它给出的正常的消息
[GIN] 2025/04/16 - 07:12:16 | 200 |  31.43531627s |      172.18.0.5 | POST     "/api/generate"，然而还是出现了问题：
From http://host.docker.internal:30000/zrl/test1
 * branch            master     -> FETCH_HEAD
aiGenerate: Error: Failed to parse JSON response
    at IncomingMessage.<anonymous> (/run/act/actions/fae9481ca80106fca335154d31806d6f0f4ce450[2](http://localhost:30000/zrl/test1/actions/runs/31#jobstep-2-2)8dd9db4b4689e65bcfac12e/dist/utils.js:72:28)
    at IncomingMessage.emit (node:events:529:[3](http://localhost:30000/zrl/test1/actions/runs/31#jobstep-2-3)5)
    at endReadableNT (node:internal/streams/readable:1[4](http://localhost:30000/zrl/test1/actions/runs/31#jobstep-2-4)00:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
检查结束
这是为什么呢？或者说可能的原因有哪些呢？跟ollama或者使用的模型有关吗？我试过 deepseek-coder-v2:16b 和 llama3:8b，都报这个错误，并且ollama都正常的

**Comment by celing76** [comment]
改为main之后，code review 是这个错误
From http://host.docker.internal:30000/zrl/test1
 * branch            master     -> FETCH_HEAD
aiGenerate: Error: Failed to parse :<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.[2](http://localhost:30000/zrl/test1/actions/runs/35#jobstep-2-2)6.3</center>
</body>
</html>
    at IncomingMessage.<anonymous> (/run/act/actions/164ac[3](http://localhost:30000/zrl/test1/actions/runs/35#jobstep-2-3)5e68879eebe3af28ca12f729e6a46cd7b02e7bd751ee1a21e9c[4](http://localhost:30000/zrl/test1/actions/runs/35#jobstep-2-4)43328c/dist/utils.js:72:28)
    at IncomingMessage.emit (node:events:[5](http://localhost:30000/zrl/test1/actions/runs/35#jobstep-2-5)29:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:[8](http://localhost:30000/zrl/test1/actions/runs/35#jobstep-2-8)2:21)
检查结束

**Comment by kekxv** [comment]
检查一下你的接口

**Comment by celing76** [comment]
我检查了一下nginx的日志，在出错时，它显示了这样的信息
172.18.0.5 - - [16/Apr/2025:08:09:28 +0000] "POST /api/generate HTTP/1.1" 200 3769 "-" "-" "-"

**Comment by kekxv** [comment]
你这边输出的内容，不是完整的json格式，你用curl测试看看吧

**Comment by celing76** [comment]
我用curl测试了一下输出的是完整的json格式，这个输出的不完整是因为我在代码里加了限制，只让他输出前1000个字符，我又改了一下，让它输出完整json格式的数据，如下
{"model":"llama3:8b","created_at":"2025-04-16T10:17:28.475877727Z","response":"**反馈详情**\n================\n\n本次评估的修改代码风险分为 3 级别，以下是详细的反馈内容：\n\n* 该修改添加了一行 `printf` 语句用于输出测试AI代码注释，风险级别为 1。\n\t+ 建议将此语句替换为日志记录或 debug 模式，以便更好地跟踪和调试应用程序。\n\t+ 优先级：高\n\n总体而言，这次修改的风险较低，但仍需要注意对日志记录和 debug 模式的使用，以确保应用程序的可靠性。","done":true,"done_reason":"stop","context":[128006,9125,128007,1432,5618,5296,430,499,527,264,4500,6335,11,323,701,3465,374,311,3477,264,743,315,6958,7540,13,21883,527,279,3477,7504,499,1205,311,1833,382,2675,690,5371,264,1160,315,41640,323,872,7276,2262,11,719,387,8010,430,499,1253,539,617,279,4686,2082,2317,13,5321,1193,3477,279,5238,315,2082,430,617,5614,304,279,6958,7540,320,17249,477,11309,5238,570,578,2082,374,4528,311,279,2612,315,279,16749,3722,3290,13,55217,5238,527,82595,449,264,28382,1879,78323,323,3779,5238,527,82595,449,264,5636,1879,6768,3343,7089,5238,3493,2317,719,1288,387,12305,369,279,3477,323,1288,539,387,29786,389,382,4599,47614,279,5614,2082,11,4587,1005,264,5326,20413,1887,4528,311,279,8241,8440,5573,11,449,264,2134,505,220,16,311,220,20,11,1405,220,16,15151,279,15821,5326,315,54477,279,2082,1139,279,2082,3231,323,220,20,15151,279,8592,5326,430,1253,1121,304,3738,15293,1694,11102,477,20451,382,644,701,11302,11,11415,4754,23367,11,4284,5627,311,1304,279,2082,810,64694,11,323,35608,279,5178,315,279,15840,4221,13,69352,5292,904,5446,7039,477,24511,430,3073,304,61947,439,1579,5326,11,3493,264,5573,11,323,2612,279,5446,7039,477,24511,13,1442,8581,11,5573,279,4442,3196,389,37023,926,16565,382,5618,656,539,4068,389,45473,5865,1139,9333,11,810,71128,6305,7389,433,374,264,5199,4360,13,23212,11,387,8010,430,1063,20797,323,12823,499,1253,539,387,11537,449,690,387,1511,11,779,656,539,4068,389,1884,7389,499,527,3738,1070,374,264,3575,382,8144,701,11302,3649,304,74292,3645,13,3234,539,2997,41640,477,5326,5990,304,701,11302,3649,13,4815,65539,430,701,11302,3649,527,64694,11,2867,11,13687,11,323,6721,13,1442,499,4284,5361,18637,11,1005,459,11713,1160,311,13519,279,10844,315,279,4442,13,4815,2675,2011,6013,1193,304,8620,311,682,44983,0,5321,3493,2867,323,13687,11503,304,8620,4221,4999,128009,128006,882,128007,271,13798,1198,13178,264,16169,8747,2356,587,32706,16169,8747,2356,587,32706,7356,293,16169,8747,2356,587,32706,16169,8747,2356,587,32706,7356,198,1275,220,23,64,16332,370,497,64,22,65,21278,68,220,1041,21975,198,4521,264,16169,8747,2356,587,32706,16169,8747,2356,587,32706,7356,198,63830,293,16169,8747,2356,587,32706,16169,8747,2356,587,32706,7356,198,19741,482,1490,11,20,489,1490,11,21,23107,16982,6290,8747,2356,587,32706,2213,487,3888,2584,746,220,72751,8747,2356,587,32706,28437,41971,280,220,2157,623,6334,24081,284,612,60140,280,220,71614,21311,308,2647,284,41971,34696,8240,545,10,6203,446,82805,15836,47200,26130,69962,803,220,862,7989,280,457,128009,128006,78191,128007,271,334,95543,46065,230,90756,1035,1547,271,22656,33671,64479,112494,9554,26239,47200,122530,17620,18184,220,18,106992,100,64022,3922,88852,21043,67933,105986,9554,95543,46065,230,44915,49543,9,220,76982,26239,43955,104430,23039,1595,2578,63,220,73981,106808,114593,67117,82805,15836,47200,26130,69962,3922,122530,53434,64022,18184,220,16,9174,197,10,111789,97522,45163,33091,73981,106808,109913,72234,18184,9080,78228,66677,58291,7542,6704,45501,29430,105610,102924,34226,53901,30590,104142,111930,103,34208,48972,42421,109589,75320,9174,197,10,220,91272,61826,53434,5232,45736,271,60843,33014,69636,78244,103138,33671,26239,9554,122530,105842,103167,102378,110618,86206,61633,33764,9080,78228,66677,34208,7542,6704,45501,29430,9554,38129,105610,35056,33563,109589,75320,9554,31540,110445,34171,1811],"total_duration":11679916024,"load_duration":9162155813,"prompt_eval_count":533,"prompt_eval_duration":312962320,"eval_count":141,"eval_duration":2203231830}
但是没看到自动评论

**Comment by celing76** [comment]
我看了一下，我的工作流文件是直接复制的你写的这个
```
name: ai-reviews

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    name: Review PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Review code
        uses: kekxv/AiReviewPR@v0.0.5
        with:
          model: 'gemma2:2b'
          host: ${{ vars.OLLAMA_HOST }}
          ai_token: ${{ secrets.AI_TOKEN }}
          REVIEW_PULL_REQUEST: false
          exclude_files: |
            ^.+\.md
            test2\.js
```
然后我看到你在下面的输入参数里面还有一些没有写在这里面的，比如
LANGUAGE
描述: 使用语言（中文）。
默认值: "Chinese"。
token
描述: 用于访问存储库的个人访问令牌（PAT）。该令牌配置在本地 git 配置中，允许脚本运行经过身份验证的 git 命令。作业结束时会移除 PAT。
建议: 使用权限最少的服务账号生成新的 PAT 并仅选择必要的作用域。
文档链接: [了解如何创建和使用加密密钥](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)。
默认值: ${{ github.token }}。
像这些输入参数我都没有写在我的工作流文件里面，是不是这个导致了不能生成评论？

**Comment by kekxv** [comment]
这部份看看：
<img width="631" alt="Image" src="https://github.com/user-attachments/assets/630eee59-1adb-43b7-954a-4d8dc319a4d6" />

**Comment by celing76** [comment]
![Image](https://github.com/user-attachments/assets/f78dad24-9ba4-446b-af84-7f24ed6adeb4)
如图，之前还会显示  “检查结束” 的提示，现在连这个提示都不显示了

**Comment by kekxv** [comment]
这部份删掉，有可能是输出长度超出了，后续不显示
https://github.com/celing76/AiReviewPR/blob/2b96d78136ef61899090ee1c6467f310885642aa/dist/utils.js#L65-L70

**Comment by celing76** [comment]
![Image](https://github.com/user-attachments/assets/9b3deda5-6e5c-4ad8-86fb-1daad81d0a86)
删掉之后是这样的，很奇怪。

**Comment by kekxv** [comment]
你把你改过之后的代码贴一下

**Comment by celing76** [comment]
`        const req = (url_.protocol === "http:" ? http_1.default : https_1.default).request(options, (res) => {
            let responseBody = '';
            // !!! 添加这一行来显式设置响应编码 !!!
            res.setEncoding('utf8');
            res.on('data', (chunk) => {
                responseBody += chunk;
            });
            res.on('end', () => {
                //console.log("--- [Action Debug] Received full response body ---");
                //console.log(responseBody);
                //console.log("--- [Action Debug] End of response body sample ---");
                try {
                } catch (error) {
                    console.error("--- [Action Debug] JSON Parse Error ---");
                    console.error("Error message:", error.message);
                    // 打印导致失败的响应体片段
                    console.error("Response body that failed parsing (first 1000 chars):", responseBody);
                    reject(new Error('Failed to parse JSON response'));
                }
            });
        });`
这个是改过的代码

**Comment by celing76** [comment]
```
        const req = (url_.protocol === "http:" ? http_1.default : https_1.default).request(options, (res) => {
            let responseBody = '';
            // !!! 添加这一行来显式设置响应编码 !!!
            res.setEncoding('utf8');
            res.on('data', (chunk) => {
                responseBody += chunk;
            });
            res.on('end', () => {
                //console.log("--- [Action Debug] Received full response body ---");
                //console.log(responseBody);
                //console.log("--- [Action Debug] End of response body sample ---");
                try {
                } catch (error) {
                    console.error("--- [Action Debug] JSON Parse Error ---");
                    console.error("Error message:", error.message);
                    // 打印导致失败的响应体片段
                    console.error("Response body that failed parsing (first 1000 chars):", responseBody);
                    reject(new Error('Failed to parse JSON response'));
                }
            });
        });
```
这部分是改过的代码

**Comment by kekxv** [comment]
你没有调用： `resolve`
https://github.com/kekxv/AiReviewPR/blob/82d4b06f354fc1d99adb7f12ece06136719f0e25/dist/utils.js#L64-L69

**Comment by kekxv** [comment]
`192.168.65.254:80`是你的gitea服务？是的话，检查一下日志，或者看看是否无法访问

**Comment by kekxv** [comment]
应该是这里获取的系统地址`GITHUB_API_URL`，你的配置似乎不对：
https://github.com/kekxv/AiReviewPR/blob/82d4b06f354fc1d99adb7f12ece06136719f0e25/src/index.ts#L35

**Comment by celing76** [comment]
```
name: ai-reviews

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    name: Review PR
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Review code
        uses: kekxv/AiReviewPR@main
        with:
          model: 'deepseek-coder-v2:16b'
          host: 'http://ollama-port-proxy'
          ai_token: ${{ secrets.AI_TOKEN }}
          REVIEW_PULL_REQUEST: false
          exclude_files: |
            ^.+\.md
            test2\.js
```
这里是我的配置，有什么不对的吗？
